language: python
os: linux
sudo: required
dist: xenial
notifications:
    email: false

python:
    - 3.6
services:
    - mysql

before_install:
    - pip install black
    - pip install future

install:
    - pip install .[tests]

before_script:
    - mysql -e "CREATE DATABASE test;"

script:
    - black --check .
    - pytest -x
