language: python
os: linux
sudo: required
dist: xenial

python:
    - 3.6
notifications:
    email: false
addons:
  ssh_known_hosts:
    - bitbucket.org
  apt:
      packages:
          - libhdf5-serial-dev


before_install:
    - pip install black
    - pip install future
    - pip install pytest
    -
install:
    - pip install .

script:
    # Run black on all .py files in all subfolders
    - black --check .
