language: python
os: linux
sudo: required
dist: xenial

python:
    - 3.6
notifications:
    email: false


before_install:
    - pip install black
    - pip install future

install:
    - pip install .

script:
    - black --check .
    - python3 -m unittest discover -s test -v
