name: chimedb-ci-build
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:

  black-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Install black
      run: pip install black

    - name: Check code with black
      run: |
        black --check .

  ruff-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Install chimedb.core
      run: pip install .

    - name: Install ruff
      run: pip install ruff

    - name: Check code with ruff
      run: ruff check .

  run-tests:
    strategy:
      matrix:
        python-version: ["3.9", "3.12"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install chimedb
      run: |
        pip install .[tests]

    - name: Run tests
      run: pytest .
